a =int(input("Enter the value of a: "))
b =int(input("Enter the value of b: "))
print("Comparison of a and b",a>b)
print("Comparison of a and b",a<b)
print("Comparison of a and b",a==b)
print("Comparison of a and b",a!=b)
print("Comparison of a and b",a>=b)
print("Comparison of a and b",a<=b)
